language: php

php:
  - 5.3
  - 5.4
  - 5.5

services: redis

before_script:
  - wget https://github.com/nicolasff/phpredis/archive/2.2.5.zip -O php-redis.zip
  - unzip php-redis.zip
  - cd phpredis-2.2.5/
  - phpize
  - ./configure
  - make && make install
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ../
  - rm -R phpredis-2.2.5/
  - phpenv rehash
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v